# Generated by Django 5.1.7 on 2025-03-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=5)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('number_of_matches', models.IntegerField(default=0)),
                ('number_of_shuttlecock', models.IntegerField(default=0)),
            ],
        ),
    ]
